# Generated by Django 3.0.6 on 2020-05-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
